{% set name = "oslo.i18n" %}
{% set version = "3.22.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "dccc5d4f3c0976917a47de709f4e49db1b3ce790bdadc852e38238f9cdb94b0d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - babel !=2.4.0,>=2.3.4
    - six >=1.10.0
    - fixtures

test:
  imports:
    - oslo_i18n
    - oslo_i18n.log
    - oslo_i18n.fixture

about:
  home: http://docs.openstack.org/developer/oslo.i18n/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Utilities for working with internationalization (i18n) features, especially translation for text strings in an application or library.'
  doc_url: http://docs.openstack.org/developer/oslo.i18n/
  dev_url: http://git.openstack.org/cgit/openstack/oslo.i18n

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
