{% set name = "oslo.i18n" %}
{% set version = "6.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "e2b829f205bf1eb6204756cc34027d119494b62d271feee860bf816ca7a07ead" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python >=3.6
    - pbr !=2.1.0,>=2.0.0

test:
  imports:
    - oslo_i18n

  requires:
    - pip

  commands:
    - pip check

about:
  home: http://docs.openstack.org/developer/oslo.i18n/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Utilities for working with internationalization (i18n) features, especially translation for text strings in an application or library.
  doc_url: http://docs.openstack.org/developer/oslo.i18n/
  dev_url: http://git.openstack.org/cgit/openstack/oslo.i18n

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
